WebXDAO/blockchain-dev-path

code_of_conduct.md

Signed-off-by: Ritvik Shukla <ritvikshukla261@gmail.com>

Added Code of conduct

---

README.md

Added an amazing video by 3Blue1Brown on youtube, giving a glimpse of the mathematics and concepts behind crypto currencies and blockchain

Add 3b1b's video on blockchain and crypto

---

free-training/training.md

Learn the Basics of Blockchain for free.

feat: new free course

---

learning-guide/beginner.md

A local Ethereum network designed for development.

Add Hardhat to the development guide

---

free-training/training.md

Check my commits to see what I added.

docs: add builders manual for Ethereum

---

CONTRIBUTING.md

:memo: Create CONTRIBUTING.md

---

learning-guide/beginner.md

Fixes #18
I added some amazing development videos for blockchain. So that any one who want to implement in practically they can benefited through this.

Extend List of some good tutorials

---

CONTRIBUTING.md

- Fix the invitation link in the `CONTRIBUTING.md` file.

fix: invitation link in the `CONTRIBUTING.md` file

---

learning-guide/beginner.md

No related issue (will make sure to creat one first going forward)
- Information about the related issue 
Closes: # 
Changes adds a short written path at beginning pf beginner dev path. Plan to extend this in future to give info on creating dev environment. Also adds a new section which has some recommended reading. 
Not a code change

adding material to begginner path

---

free-training/training.md

Added NFT School to the training list

Add: NFT School

---

free-training/training.md
learning-guide/beginner.md
learning-guide/medium.md

fix: Markdown linter issues

---

README.md

docs: add emojis to each section

---

free-training/training.md

Closes: #31  
The Polygon academy link is added to free training

Added Polygon Academy

---

free-training/training.md

fix: remove paid courses

---

free-training/training.md

- Added new resource for learning about web3.

#Added Resource

---

docs/💡 Learning-Guide/Advanced.md

Closes #41.
- Fix the Ethereum article link.

fix: Ethereum article link

---

LICENSE.md

Closes: #43 
- Add the MIT license.

chore: add the MIT license

---

docs/💖 Free Training/Polygon Academy.md

Closes: #50 
Changed the previous link by the Polygon academy link.

fixed the broken link of polygon academy

---

docs/🤩 Resources/Crypto Startup School.md

Add Crypto Startup School Lectures to Resources Section

---

docs/💡 Learning-Guide/Advanced.md

Added some resources
Added Resources like 
- Smart Contract Engineer, Capture the Ether and Damn Vulnerable Defi in Practice section
- Secureum in Concepts section
- Sither in Audit section

Added some resources

---

docs/💖 Free Training/SpeedRunEtherum.md

Added SpeedRunEtherum learning path.

docs: add SpeedRunEtherum

---

docs/💖 Free Training/Buildspace.md

Added Buildspace to knowledge path.

Docs: add buildspace.md entry
